dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"
dotenv: .env
dev_deployment_artifacts: True
networks:
  development:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
    weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
    fau_token: "0xFab46E002BbF0b4509813474841E0716E6730136"
    dai_usd_pricefeed: "0x777A68032a88E5A84678A77Af2CD65A7b3c0775a"
    eth_usd_pricefeed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
wallets:
  private_key: ${PRIVATE_KEY}
